Repository MOPT-UFSC/VIBRA, pull requests merged in 2025-09, with the labels that each got.

#178 Add color and texture scheme for model attributes
  vibra/__init__.py
  vibra/interface/data/textures/chess_texture.jpg
  vibra/interface/data/textures/metal_normal.jpg
  vibra/interface/data/textures/perforated_normal.jpg
  vibra/interface/data/textures/perforated_opacity.png
  vibra/interface/data/textures/porous_normal.jpg
  vibra/interface/data/textures/wall_texture.png
  vibra/interface/main_window.py
  vibra/interface/viewer_3d/actors/lines_actor.py
  vibra/interface/viewer_3d/actors/multimaterial.py
  vibra/interface/viewer_3d/render_widgets/geometry_render_widget.py
  vibra/interface/viewer_3d/selection/common_selection.py
  vibra/interface/viewer_3d/selection/geometry_selection.py
  vibra/interface/viewer_3d/sources/arrows.py
  vibra/interface/viewer_3d/sources/complex_shapes.py
  vibra/interface/viewer_3d/sources/simple_shapes.py
  vibra/utils/polydata_utils.py
  vibra/utils/vtk_utils.py
Labels: Feature request :pray:

#190 New viscous thermal loss
  vibra/engine/dissipation_models/viscous_thermal_loss_models.py
  vibra/interface/data/examples/vibra_files/curve_L.vibra
  vibra/interface/data/icons/resources_rc.py
  vibra/interface/data/ui_files/model/setup/acoustic/viscous_thermal_model_inputs.ui
  vibra/interface/model_inputs/acoustic/circular_duct_data.py
  vibra/interface/model_inputs/acoustic/rectangular_duct_data.py
  vibra/interface/model_inputs/acoustic/viscous_thermal_loss_model_inputs.py
  vibra/interface/ui_generated/mesh/mesher_setup_ui.py
  vibra/interface/ui_generated/model/setup/acoustic/viscous_thermal_model_inputs_ui.py
  vibra/interface/ui_generated/plots/acoustic/specific_acoustic_impedance_inputs_ui.py
  vibra/project_files/load_project.py
  vibra/project_files/project_file.py
Labels: Feature request :pray:

#184 Refactor linear solver to handle symmetric and complex inputs
  tests/advanced/validate_acoustic_element_tet10.py
  tests/advanced/validate_acoustic_element_tet10_harmonic.py
  tests/advanced/validate_acoustic_element_tet10_modal.py
  tests/advanced/validate_acoustic_element_tet4_harmonic.py
  tests/advanced/validate_acoustic_element_tet4_modal.py
  tests/advanced/validate_mass_source_tet10.py
  tests/advanced/validate_mass_source_tet4.py
  tests/advanced/validate_porous_material_for_silencer.py
  tests/advanced/validate_porous_material_for_silencer_refined_mesh.py
  tests/advanced/validate_shell_element.py
  tests/advanced/validate_shell_for_Lpipe.py
  tests/advanced/validate_shell_for_piping_example.py
  tests/advanced/validate_transmission_loss_for_complex_impedances.py
  tests/advanced/validate_viscous_thermal_loss_models.py
  tests/general/test_modal_acoustic_solver.py
  tests/general/test_modal_structural_solver.py
  vibra/engine/assemblers/acoustic_assembler.py
  vibra/engine/assemblers/structural_assembler.py
  vibra/engine/elements/elements_1d/acoustic_line2_element.py
  vibra/engine/elements/elements_1d/acoustic_line3_element.py
  vibra/engine/elements/elements_2d/acoustic/acoustic_quad4_element.py
  vibra/engine/elements/elements_2d/acoustic/acoustic_tria3_element.py
  vibra/engine/elements/elements_2d/acoustic/acoustic_tria6_element.py
  vibra/engine/elements/elements_2d/structural/structural_tria3_element.py
  vibra/engine/elements/elements_3d/acoustic/acoustic_hex20_element.py
  vibra/engine/elements/elements_3d/acoustic/acoustic_hex8_element.py
  vibra/engine/elements/elements_3d/acoustic/acoustic_tet10_element.py
  vibra/engine/elements/elements_3d/acoustic/acoustic_tet4_element.py
  vibra/engine/elements/elements_3d/structural/structural_hex20_element.py
  vibra/engine/elements/elements_3d/structural/structural_hex8_element.py
  vibra/engine/elements/elements_3d/structural/structural_tet10_element.py
  vibra/engine/elements/elements_3d/structural/structural_tet4_element.py
  vibra/engine/model.py
  vibra/engine/postprocessing/acoustic_postprocessing.py
  vibra/engine/postprocessing/structural_postprocessing.py
  vibra/engine/solvers/__init__.py
  vibra/engine/solvers/_tests/test_acoustic_harmonic_solver.py
  vibra/engine/solvers/acoustic_harmonic_solver.py
  vibra/engine/solvers/acoustic_modal_solver.py
  vibra/engine/solvers/harmonic_solver.py
  vibra/engine/solvers/linear_solver.py
  vibra/engine/solvers/modal_solver.py
  vibra/engine/solvers/structural_harmonic_solver.py
  vibra/engine/solvers/structural_modal_solver.py
  vibra/interface/model_inputs/structural/distributed_loads_inputs.py
  vibra/interface/model_inputs/structural/dof_prescription_inputs.py
  vibra/interface/model_inputs/structural/nodal_loads_inputs.py
  vibra/interface/plots/acoustic/acoustic_impedance_inputs.py
  vibra/interface/plots/acoustic/particle_velocity_inputs.py
  vibra/interface/plots/acoustic/surface_absorption_coefficient_inputs.py
  vibra/interface/plots/acoustic/transmission_loss_inputs.py
  vibra/interface/plots/structural/structural_frequency_response_inputs.py
  vibra/interface/viewer_3d/render_widgets/results_render_widget.py
  vibra/project_files/lazy_hdf5_matrix.py
  vibra/project_files/load_project.py
  vibra/project_files/project.py
  vibra/project_files/project_file.py
Labels: Nice to have :bulb:

#205 Fixes behavior bug in magnification factor slider
  vibra/interface/animation_toolbar.py
Labels: Bug :bug:

#204 Implements a temporary stop button
  vibra/engine/assemblers/acoustic_assembler.py
  vibra/engine/model.py
  vibra/engine/solvers/harmonic_solver.py
  vibra/interface/analysis_toolbar.py
  vibra/interface/data/ui_files/messages/loading_window.ui
  vibra/interface/loading_window.py
  vibra/interface/process_analysis.py
  vibra/interface/ui_generated/messages/loading_window_ui.py
  vibra/project_files/project.py
Labels: Nice to have :bulb:
